#server
server:
  port: 8080
#jdbc
spring:
  application:
    name: consumer-service
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka,http://127.0.0.1:8083/eureka