#server
server:
  port: 8080
#jdbc
spring:
  application:
    name: consumer-service
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka
feign:
  hystrix:
    enabled: true

ribbon:
  ConnectionTimeOut: 500
  ReadTimeOut: 2000
#hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1200